services:
  schoolapi:
    build:
      context: .
      dockerfile: src/SchoolAPI/SchoolApi/Dockerfile           
    ports:
      - "5039:5039"
    networks:
      - gateway_network

  userapi:
    build:
      context: .      
      dockerfile: src/Users/UserAPI/Dockerfile       
    ports:
      - "5050:5050"
    networks:
      - gateway_network

  ocelotgateway:
    build:
      context: .
      dockerfile: src/OcelotGateway/Dockerfile
    ports:
      - "5273:5273"
    networks:
      - gateway_network
    depends_on:
      - schoolapi
      - userapi

networks:
  gateway_network:
    driver: bridge
